const data = {
    "2":{
      "Functional Hypertrophy":{
        1: [["Bench Press", 3, "5-8"], 
        ["Pec-Dec", 3, "5-8"], 
        ["Pull Ups/Assisted Pull Ups", 3, "5-8"],
        ["Close-Grip Cable Row", 3, "5-8"], 
        ["Dumbbell Shoulder Press", 3, "5-8"]],
        2: ["rest"],
        3: ["rest"],
        4: ["rest"],
        5: [["Barbell Squats", 3, "5-8"], 
        ["Romanian Deadlifts", 3, "5-8"], 
        ["Leg Extensions", 3, "5-8"],
        ["Leg Curls", 3, "5-8"], 
        ["Adductors", 3, "5-8"]],
        6: ["rest"],
        7: ["rest"],
        8: [["Incline Bench Press", 3, "5-8"], 
        ["ISO Lateral Pulldown Machine", 3, "5-8"],
        ["Wide-Grip Cable Row", 3, "5-8"], 
        ["Lateral Raise Machine", 3, "5-8"],
        ["V-bar Pushdown", 3, "5-8"],
        ["EZ Bar Curls", 3, "5-8"]],
        9: ["rest"],
        10: ["rest"],
        11: ["rest"],
        12: [["Deadlifts", 3, "5-8"], 
        ["Hack Squat", 3, "5-8"], 
        ["Leg Curls", 3, "5-8"],
        ["Leg Extensions", 3, "5-8"], 
        ["Calf Raises", 3, "5-8"]],
        13: ["rest"],
        14: ["rest"]},
      "Hypertrophy": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["rest"],
        4: ["rest"],
        5: ["workout", "another"] ,
        6: ["rest"],
        7: ["rest"]},
      "Powerlifting": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["rest"],
        4: ["rest"],
        5: ["workout", "another"] ,
        6: ["rest"],
        7: ["rest"]}, 
    } ,
    "3":{
      "Strength":{
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["rest"],
        5: ["workout", "another"] ,
        6: ["rest"],
        7: ["rest"]},
      "Muscle-building": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["rest"],
        5: ["workout", "another"] ,
        6: ["rest"],
        7: ["rest"]},
      "Powerlifting": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["rest"],
        5: ["workout", "another"] ,
        6: ["rest"],
        7: ["rest"]}
    } ,
    "4":{
      "Strength":{
        1: ["rest"],
        2: ["workout", "another"],
        3: ["rest"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]},
      "Muscle-building": {
        1: ["rest"],
        2: ["workout", "another"],
        3: ["rest"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]},
      "Powerlifting": {
        1: ["rest"],
        2: ["workout", "another"],
        3: ["rest"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]}
    } ,
    "5":{
      "Strength":{
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]},
      "Muscle-building": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]},
      "Powerlifting": {
        1: ["workout", "another"],
        2: ["rest"],
        3: ["workout", "another"],
        4: ["workout", "another"],
        5: ["rest"] ,
        6: ["workout", "another"],
        7: ["workout", "another"]}
    } ,
    "6":{
      "Strength":{
        1: [["bench", 3, "4-6"], "another"],
        2: [["bench", 3, "4-6"], "another"],
        3: [["bench", 3, "4-6"], "another"],
        4: ["rest"]},
        
      "Muscle-building": {
        1: [["bench", 3, "4-6"], "another"],
        2: [["bench", 3, "4-6"], "another"],
        3: [["bench", 3, "4-6"], "another"],
        4: ["rest"]},
      "Powerlifting": {
        1: [["bench", 3, "4-6"], "another"],
        2: [["bench", 3, "4-6"], "another"],
        3: [["bench", 3, "4-6"], "another"],
        4: ["rest"]},
    } ,
    1: [["bench", 3, "4-6"], "another"],
        2: [["bench", 3, "4-6"], "another"],
        3: [["bench", 3, "4-6"], "another"],
        4: ["rest"]},
    
    

}

