const data = {
  "2": {
    "Functional Hypertrophy":{
      1: [["Bench Press", 3, "5-8"], 
      ["Pec-Dec", 3, "5-8"], 
      ["Pull Ups/Assisted Pull Ups", 3, "5-8"],
      ["Close-Grip Cable Row", 3, "5-8"], 
      ["Dumbbell Shoulder Press", 3, "5-8"]],
      2: ["rest"],
      3: ["rest"],
      4: ["rest"],
      5: [["Barbell Squats", 3, "5-8"], 
      ["Romanian Deadlifts", 3, "5-8"], 
      ["Leg Extensions", 3, "5-8"],
      ["Leg Curls", 3, "5-8"], 
      ["Adductors", 3, "5-8"]],
      6: ["rest"],
      7: ["rest"],
      8: [["Incline Bench Press", 3, "5-8"], 
      ["ISO Lateral Pulldown Machine", 3, "5-8"],
      ["Wide-Grip Cable Row", 3, "5-8"], 
      ["Lateral Raise Machine", 3, "5-8"],
      ["V-bar Pushdown", 3, "5-8"],
      ["EZ Bar Curls", 3, "5-8"]],
      9: ["rest"],
      10: ["rest"],
      11: ["rest"],
      12: [["Deadlifts", 3, "5-8"], 
      ["Hack Squat", 3, "5-8"], 
      ["Leg Curls", 3, "5-8"],
      ["Leg Extensions", 3, "5-8"], 
      ["Calf Raises", 3, "5-8"]],
      13: ["rest"],
      14: ["rest"]
      },
    "Hypertrophy": {
      1: [["Incline Dumbbell Press", 3, "8-12"],
          ["Pec-Dec", 3, "8-12"],
          ["Lat Pullover", 3, "8-12"],
          ["Dumbbell Row", 3, "8-12"],
          ["Lateral Raises", 3, "8-12"]],
      2: ["rest"],
      3: ["rest"],
      4: ["rest"],
      5: [["Deadlifts", 3, "5-8"], 
      ["Leg Press", 3, "5-8"], 
      ["Leg Curls", 3, "5-8"],
      ["Leg Extensions", 3, "5-8"], 
      ["Adductors", 3, "5-8"]],
      6: ["rest"],
      7: ["rest"],
      8: [["Dumbbell Bench Press", 3, "5-8"], 
      ["ISO Lateral Pulldown Machine", 3, "5-8"],
      ["Wide-Grip Row Machine", 3, "5-8"], 
      ["Lateral Raise Machine", 3, "5-8"],
      ["V-bar Pushdown", 3, "5-8"],
      ["EZ Bar Curls", 3, "5-8"]],
      9: ["rest"],
      10: ["rest"],
      11: ["rest"],
      12: [["Deadlifts", 3, "5-8"], 
      ["Leg Press", 3, "5-8"], 
      ["Leg Curls", 3, "5-8"],
      ["Leg Extensions", 3, "5-8"], 
      ["Calf Raises", 3, "5-8"]],
      13: ["rest"],
      14: ["rest"]
    },
    "Strength": {
      1: [["Squats", 5, "3-5"],
          ["Deadlifts", 5, "3-5"],
          ["Bench Press", 5, "3-5"],
          ["Overhead Press", 5, "3-5"],
          ["Barbell Rows", 5, "3-5"]],
      2: ["rest"],
      3: ["rest"],
      4: ["rest"],
      5: [["Pull-Ups", 5, "3-5"],
          ["Front Squats", 5, "3-5"],
          ["Incline Bench Press", 5, "3-5"],
          ["Leg Press", 5, "3-5"],
          ["Bulgarian Split Squats", 5, "3-5"]],
      6: ["rest"],
      7: ["rest"],
    },
  },
  "3": {
    "Functional Hypertrophy": {
      1: [["Lat Pulldowns", 3, "5-8"],
          ["T-Bar Row", 3, "5-8"],
          ["Kneeling Single-Arm Cable Lat-Pulldown", 3, "5-8"],
          ["EZ Bar Curls", 3, "5-8"],
          ["Preacher Curls", 3, "5-8"],
          ["Face Pulls", 3, "5-8"]],
      2: ["rest"],
      3: [["Barbell Bench Press", 3, "5-8"],
          ["Pec-Dec", 3, "5-8"],
          ["Dumbbell Shoulder Press", 3, "5-8"],
          ["JM Press", 3, "5-8"],
          ["EZ Bar Skullcrusher", 3, "5-8"]],
      4: ["rest"],
      5: [["Squats", 3, "5-8"],
          ["Deadlifts", 3, "5-8"],
          ["Leg Extensions", 3, "5-8"],
          ["Leg Curls", 3, "5-8"],
          ["Calf Raises", 3, "5-8"]],
      6: ["rest"],
      7: ["rest"],
    },
    "Hypertrophy": {
      1: [["Dumbbell Flyes", 3, "8-12"],
          ["Lat Pulldown", 3, "8-12"],
          ["Leg Press", 3, "8-12"],
          ["Lateral Raises", 3, "8-12"],
          ["Cable Tricep Extensions", 3, "8-12"]],
      2: ["rest"],
      3: [["Barbell Squats", 3, "8-12"],
          ["Incline Bench Press", 3, "8-12"],
          ["Dumbbell Rows", 3, "8-12"],
          ["Bicep Curls", 3, "8-12"],
          ["Lunges", 3, "8-12"]],
      4: ["rest"],
      5: [["Deadlifts", 3, "8-12"],
          ["Bench Press", 3, "8-12"],
          ["Leg Curls", 3, "8-12"],
          ["Seated Dumbbell Shoulder Press", 3, "8-12"],
          ["Plank", 3, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
    "Strength": {
      1: [["Barbell Squats", 5, "3-5"],
          ["Deadlifts", 5, "3-5"],
          ["Bench Press", 5, "3-5"],
          ["Overhead Press", 5, "3-5"],
          ["Barbell Rows", 5, "3-5"]],
      2: ["rest"],
      3: [["Pull-Ups", 5, "3-5"],
          ["Front Squats", 5, "3-5"],
          ["Incline Bench Press", 5, "3-5"],
          ["Leg Press", 5, "3-5"],
          ["Lunges", 5, "3-5"]],
      4: ["rest"],
      5: [["Romanian Deadlifts", 5, "3-5"],
          ["Barbell Bench Press", 5, "3-5"],
          ["T-Bar Rows", 5, "3-5"],
          ["Seated Shoulder Press", 5, "3-5"],
          ["Farmer's Walk", 5, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
  },
  "4": {
    "Functional Hypertrophy": {
      1: [["Leg Press", 3, "5-8"],
          ["Chest Fly", 3, "5-8"],
          ["Pull-Ups", 3, "5-8"],
          ["Dumbbell Shoulder Press", 3, "5-8"],
          ["Calf Raises", 3, "5-8"]],
      2: ["rest"],
      3: [["Barbell Squats", 3, "5-8"],
          ["Lat Pulldown", 3, "5-8"],
          ["Incline Dumbbell Press", 3, "5-8"],
          ["Cable Rows", 3, "5-8"],
          ["Plank", 3, "30-60 seconds"]],
      4: ["rest"],
      5: [["Deadlifts", 3, "5-8"],
          ["Bench Press", 3, "5-8"],
          ["Leg Curls", 3, "5-8"],
          ["Lateral Raises", 3, "5-8"],
          ["Dumbbell Rows", 3, "5-8"]],
      6: ["rest"],
      7: ["rest"],
    },
    "Hypertrophy": {
      1: [["Incline Bench Press", 3, "8-12"],
          ["Dumbbell Flyes", 3, "8-12"],
          ["Seated Row", 3, "8-12"],
          ["Leg Extensions", 3, "8-12"],
          ["Cable Tricep Extensions", 3, "8-12"]],
      2: ["rest"],
      3: [["Barbell Squats", 3, "8-12"],
          ["Pull-Ups", 3, "8-12"],
          ["Incline Dumbbell Press", 3, "8-12"],
          ["Dumbbell Rows", 3, "8-12"],
          ["Lateral Raises", 3, "8-12"]],
      4: ["rest"],
      5: [["Deadlifts", 3, "8-12"],
          ["Bench Press", 3, "8-12"],
          ["Leg Curls", 3, "8-12"],
          ["Seated Shoulder Press", 3, "8-12"],
          ["Plank", 3, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
    "Strength": {
      1: [["Barbell Squats", 5, "3-5"],
          ["Deadlifts", 5, "3-5"],
          ["Bench Press", 5, "3-5"],
          ["Overhead Press", 5, "3-5"],
          ["Barbell Rows", 5, "3-5"]],
      2: ["rest"],
      3: [["Pull-Ups", 5, "3-5"],
          ["Front Squats", 5, "3-5"],
          ["Incline Bench Press", 5, "3-5"],
          ["Leg Press", 5, "3-5"],
          ["Lunges", 5, "3-5"]],
      4: ["rest"],
      5: [["Romanian Deadlifts", 5, "3-5"],
          ["Barbell Bench Press", 5, "3-5"],
          ["T-Bar Rows", 5, "3-5"],
          ["Seated Shoulder Press", 5, "3-5"],
          ["Farmer's Walk", 5, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
  },
  "5": {
    "Functional Hypertrophy": {
      1: [["Bench Press", 3, "5-8"],
          ["Pull-Ups", 3, "5-8"],
          ["Incline Dumbbell Press", 3, "5-8"],
          ["Dumbbell Shoulder Press", 3, "5-8"],
          ["Cable Row", 3, "5-8"]],
      2: ["rest"],
      3: [["Leg Press", 3, "5-8"],
          ["Deadlifts", 3, "5-8"],
          ["Seated Row", 3, "5-8"],
          ["Lateral Raises", 3, "5-8"],
          ["Plank", 3, "30-60 seconds"]],
      4: [["Barbell Squats", 3, "5-8"],
          ["Incline Dumbbell Flyes", 3, "5-8"],
          ["Tricep Dips", 3, "5-8"],
          ["Bicep Curls", 3, "5-8"],
          ["Calf Raises", 3, "5-8"]],
      5: ["rest"],
      6: [["Deadlifts", 3, "5-8"],
          ["Bench Press", 3, "5-8"],
          ["Leg Curls", 3, "5-8"],
          ["Shoulder Press", 3, "5-8"],
          ["Pull-Ups", 3, "5-8"]],
      7: ["rest"],
    },
    "Hypertrophy": {
      1: [["Incline Dumbbell Press", 3, "8-12"],
          ["Dumbbell Rows", 3, "8-12"],
          ["Lat Pulldown", 3, "8-12"],
          ["Leg Extensions", 3, "8-12"],
          ["Cable Tricep Extensions", 3, "8-12"]],
      2: ["rest"],
      3: [["Barbell Squats", 3, "8-12"],
          ["Pull-Ups", 3, "8-12"],
          ["Incline Dumbbell Press", 3, "8-12"],
          ["Dumbbell Rows", 3, "8-12"],
          ["Lateral Raises", 3, "8-12"]],
      4: ["rest"],
      5: [["Deadlifts", 3, "8-12"],
          ["Bench Press", 3, "8-12"],
          ["Leg Curls", 3, "8-12"],
          ["Seated Shoulder Press", 3, "8-12"],
          ["Plank", 3, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
    "Strength": {
      1: [["Barbell Squats", 5, "3-5"],
          ["Deadlifts", 5, "3-5"],
          ["Bench Press", 5, "3-5"],
          ["Overhead Press", 5, "3-5"],
          ["Barbell Rows", 5, "3-5"]],
      2: ["rest"],
      3: [["Pull-Ups", 5, "3-5"],
          ["Front Squats", 5, "3-5"],
          ["Incline Bench Press", 5, "3-5"],
          ["Leg Press", 5, "3-5"],
          ["Lunges", 5, "3-5"]],
      4: ["rest"],
      5: [["Romanian Deadlifts", 5, "3-5"],
          ["Barbell Bench Press", 5, "3-5"],
          ["T-Bar Rows", 5, "3-5"],
          ["Seated Shoulder Press", 5, "3-5"],
          ["Farmer's Walk", 5, "30-60 seconds"]],
      6: ["rest"],
      7: ["rest"],
    },
  },
  "6": {
    "Functional Hypertrophy": {
      1: [["Bench Press", 3, "5-8"],
          ["Pull-Ups", 3, "5-8"],
          ["Dumbbell Shoulder Press", 3, "5-8"],
          ["Cable Row", 3, "5-8"],
          ["Leg Press", 3, "5-8"]],
      2: [["Incline Dumbbell Press", 3, "5-8"],
          ["T-Bar Row", 3, "5-8"],
          ["Lateral Raises", 3, "5-8"],
          ["Face Pulls", 3, "5-8"],
          ["Dumbbell Lunges", 3, "5-8"]],
      3: [["Deadlifts", 3, "5-8"],
          ["Bench Press", 3, "5-8"],
          ["Leg Curls", 3, "5-8"],
          ["Dumbbell Rows", 3, "5-8"],
          ["Plank", 3, "30-60 seconds"]],
      4: ["rest"],
    },
    "Hypertrophy": {
      1: [["Incline Dumbbell Press", 3, "8-12"],
          ["Lat Pulldown", 3, "8-12"],
          ["Leg Press", 3, "8-12"],
          ["Dumbbell Flyes", 3, "8-12"],
          ["Seated Row", 3, "8-12"]],
      2: [["Barbell Bench Press", 3, "8-12"],
          ["Cable Curls", 3, "8-12"],
          ["Leg Extensions", 3, "8-12"],
          ["Tricep Dips", 3, "8-12"],
          ["Lateral Raises", 3, "8-12"]],
      3: [["Deadlifts", 3, "8-12"],
          ["Chest Fly", 3, "8-12"],
          ["Dumbbell Rows", 3, "8-12"],
          ["Shoulder Press", 3, "8-12"],
          ["Calf Raises", 3, "8-12"]],
      4: ["rest"],
    },
    "Strength": {
      1: [["Barbell Squats", 5, "3-5"],
          ["Deadlifts", 5, "3-5"],
          ["Bench Press", 5, "3-5"],
          ["Overhead Press", 5, "3-5"],
          ["Barbell Rows", 5, "3-5"]],
      2: [["Front Squats", 5, "3-5"],
          ["Incline Bench Press", 5, "3-5"],
          ["Pull-Ups", 5, "3-5"],
          ["Leg Press", 5, "3-5"],
          ["Lunges", 5, "3-5"]],
      3: [["Romanian Deadlifts", 5, "3-5"],
          ["Barbell Bench Press", 5, "3-5"],
          ["T-Bar Rows", 5, "3-5"],
          ["Seated Shoulder Press", 5, "3-5"],
          ["Farmer's Walk", 5, "30-60 seconds"]],
      4: ["rest"],
    },

  }
};
